### ISSUE TITLE
"Cannot find module 'eslint-config-xo-react'"

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/atom-linter-xo#10]
If I try to use `eslint-config-xo-react` the linter complains it can't load the module.

The stack trace goes through `~/.atom`, I assume it's not trying the node_modules of the project. From the command line, xo works fine.

Am I missing some configuration?

package.json:
```
  "devDependencies": {
    "eslint": "^1.9.0",
    "eslint-config-xo-react": "^0.3.0",
    "eslint-plugin-react": "^3.9.0",
    "xo": "^0.11.1"
  },
  "xo": {
    "esnext": true,
    "semicolon": false,
    "env": [
      "browser",
      "mocha",
      "webpack"
    ],
    "extends": "eslint-config-xo-react"
  },
```

**Comment by sindresorhus** [comment]
`"extends": "xo-react"`

**Comment by wmertens** [comment]
no change :cry:… Anything I can do debugging-wise?

**Comment by sindresorhus** [comment]
Ah, I see the problem. Can you try reinstalling the plugin?

**Comment by wmertens** [comment]
No change, I also updated `xo` to 0.11.2 in the project and restarted Atom.

I extracted a stacktrace via the devtools:

```
Error: Cannot find module 'eslint-plugin-react
  at Module._resolveFilename (module.js:336:15
  at Function.Module._resolveFilename (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52
  at Function.Module._load (module.js:286:25
  at Module.require (module.js:365:17
  at require (module.js:384:17
  at /Users/wmertens/.atom/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/cli-engine.js:124:
  at Array.forEach (native
  at loadPlugins (/Users/wmertens/.atom/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/cli-engine.js:115:21
  at processText (/Users/wmertens/.atom/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/cli-engine.js:202:5
  at CLIEngine.executeOnText (/Users/wmertens/.atom/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/cli-engine.js:678:26
  at exports.lintText (/Users/wmertens/.atom/packages/linter-xo/node_modules/xo/index.js:107:16
  at /Users/wmertens/.atom/packages/linter-xo/index.js:17:
  at exports.allowUnsafeNewFunction (/Users/wmertens/.atom/packages/linter-xo/node_modules/loophole/lib/loophole.js:25:14
  at Object.lint (/Users/wmertens/.atom/packages/linter-xo/index.js:16:2
  at promises.push.Promise.then._this.emitter.emit.linter (/Users/wmertens/.atom/packages/linter/lib/linter-registry.js:63:26
  at /Users/wmertens/.atom/packages/linter/lib/linter-registry.js:62:
  at Set.forEach (native
  at LinterRegistry.lint (/Users/wmertens/.atom/packages/linter/lib/linter-registry.js:60:18
  at /Users/wmertens/.atom/packages/linter/lib/linter.coffee:98:
  at Emitter.module.exports.Emitter.emit (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11
  at /Users/wmertens/.atom/packages/linter/lib/editor-linter.js:80:
                                                                                       at /Users/wmertens/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by wmertens** [comment]
```
$ grep version /Users/wmertens/.atom/packages/linter-xo/node_modules/xo/package.json 
  "version": "0.11.2",
```

**Comment by sindresorhus** [comment]
There *is* a change. It now says it can't find the React plugin:

> Error: Cannot find module **'eslint-plugin-react'**

This is coming from ESLint. Since ESLint doesn't have a `cwd` option, there's no way for me to change where it looks for the plugins.

I've implemented a hack for now. Will open an issue on ESLint.

I tried it with your provided package.json config and didn't work before this fix, but works after, so should be fine now.

**Comment by wmertens** [comment]
@sindresorhus I needed to tweak it more so that it also works for files in subdirectories...

**Comment by wmertens** [comment]
The eslint issue is resolved :-D

**Comment by sindresorhus** [comment]
I noticed, but we'll have to wait until ESLint 2.0.0 stable is released.

**Comment by mastilver** [comment]
Hi guys

Is that issue resolved?

I've updated `xo` on my project
I've uninstall / reinstall xo-linter from atom

I still got the issue

**Comment by BarryThePenguin** [comment]
Seeing this too. Is it worth reopening this issue or creating a new one?

**Comment by mattbanks** [comment]
I'm seeing this issue again now. Didn't want to open a new issue since I found this closed one. Not sure if this is in xo or upstream in eslint.

global `xo` version: 0.13.0
global `eslint` version: 2.3.0
atom `linter` version: 1.11.3
atom `linter-xo` version: 0.13.0

`package.json` relevant installed packages:
```json
    "eslint-config-xo-react": "~0.5.0",
    "eslint-plugin-react": "~4.2.1",
    "xo": "~0.13.0",
```

`package.json` xo settings:
```json
"xo": {
    "ignores": [
      "build/**",
      "public/**",
      "_builds/",
      "_cache/",
      "_steps/"
    ],
    "envs": [
      "node",
      "browser"
    ],
    "globals": [
      "U",
      "html"
    ],
    "esnext": true,
    "extends": "xo-react",
    "rules": {
      "react/jsx-uses-react": 2,
      "react/jsx-uses-vars": 2,
      "react/react-in-jsx-scope": 2
    }
  }
```

Error panel in Atom:

```
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: 
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.load (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/plugins.js:116:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/plugins.js:138:21)
    at load (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/config-file.js:443:21)
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at Object.applyExtends (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config/config-file.js:338:28)
    at loadConfig (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config.js:63:37)
    at new Config (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/config.js:170:44)
    at CLIEngine.executeOnText (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/node_modules/eslint/lib/cli-engine.js:666:28)
    at exports.lintText (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/xo/index.js:13:16)
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/index.js:34:12
    at exports.allowUnsafeNewFunction (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/node_modules/loophole/lib/loophole.js:25:14)
    at Object.lint (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter-xo/index.js:33:2)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/linter-registry.js:63:26)
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/linter-registry.js:60:18)
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/editor-linter.js:80:22
    at /Users/mattbanks/.dotfiles/atom.symlink/packages/linter/lib/helpers.coffee:23:18
```

**Comment by mattbanks** [comment]
I believe the issue is in this commit: https://github.com/sindresorhus/atom-linter-xo/commit/a132bd8eaf08f87129444b4bc3e4614607162899#diff-168726dbe96b3ce427e7fedce31bb0bc

It seems like removing the hack to get around `cwd` issues with ESLint made it not work on some systems, including mine. Not sure if this hack can get put back in place for the time being or investigated @sindresorhus?

For the time being, I rolled back linter-xo v0.12.0 and it's working again here.
