### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/atom-linter-xo#12]
This happens sometimes, also for my coworkers:

1. Achieve unknown precondition
2. Run xo-fix
3. TypeError

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.10.3

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'split' of undefined
    at Function.module.exports.Range.fromText (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:49:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:549:24)
    at /Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:26
    at TextBuffer.module.exports.TextBuffer.transact (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:532:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:472:19)
    at TextEditor.module.exports.TextEditor.setText (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:707:26)
    at module.exports (/Users/wmertens/.atom/packages/linter-xo/node_modules/atom-set-text/index.js:13:9)
    at atom-text-editor.XOFix (/Users/wmertens/.atom/packages/linter-xo/index.js:81:4)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:43.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:42.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:41.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:41.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:35.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:33.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:33.7.0 XO:Fix (atom-text-editor.editor)
     -1:32.4.0 refactor:done (atom-text-editor.editor.is-focused)
     -1:32.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:31.2.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:26.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:39 core:close (atom-text-editor.editor.is-focused)
     -0:37.7.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:35.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.9.0 XO:Fix (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "my-package",
      "atom-terminal-panel",
      "language-coffee-script-angular",
      "pepper-autocomplete",
      "linter-tidy",
      "linter-python-pyflakes",
      "web-browser",
      "open-last-project",
      "livereload",
      "Coffeefilter",
      "language-javascript-semantic",
      "linter-coffeelint",
      "git-plus",
      "nuclide-diff-view",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "linter-eslint"
    ],
    "projectHome": "~/Documents/Projects",
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ],
    "destroyEmptyPanes": false,
    "packagesWithKeymapsDisabled": [
      "animated-cursor",
      "highlight-line"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
autocomplete-clang, v0.8.8
autocomplete-modules, v1.3.1
autocomplete-python, v0.10.4
browser-plus, v0.0.54
cmd-9, v0.0.3
coffee-refactor, v0.7.0
esformatter, v1.16.0
file-icons, v1.6.12
highlight-line, v0.11.0
indent-guide-improved, v1.4.4
js-refactor, v0.6.0
language-babel, v2.5.3
language-jade, v0.6.2
last-cursor-position, v0.9.0
linter, v1.11.2
linter-xo, v0.10.3
minimap, v4.16.2
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
nix, v2.1.0
project-manager, v2.6.5
refactor, v0.6.0
remote-edit, v1.8.22
tab-length, v0.1.0
tab-numbers, v0.3.0
tidy-tabs, v0.3.0

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Hard to say without anything to reproduce it with, but it kinda looks like it's coming from Atom itself.

The last stack trace item from this plugin is https://github.com/sindresorhus/atom-set-text/blob/8cd0761f83b7fdebc633e6d9edc68db8f577c586/index.js#L13.

**Comment by 5an1ty** [comment]
Same issue for me on a clean install of OSX 10.11 El Capitan with Atom 1.5.2 and using node.js 5.6 (Installed with NVM).

**Comment by zetoke** [comment]
Same issue. Just one line in file.
`import {createAction} from 'redux-actions';` - error
`import {createAction} from 'redux-actions'` - no error, autoformatting to `import {createAction} from 'redux-actions';`

**Comment by krassowski** [comment]
The same issue with newer version of atom and never version of the package, with raw config, and on Ubuntu.

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.12.0


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

TypeError: Cannot read property 'split' of undefined
    at Function.module.exports.Range.fromText (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:47:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:571:24)
    at /opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:559:26
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:557:21)
    at TextBuffer.module.exports.TextBuffer.setText (/opt/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:497:19)
    at TextEditor.module.exports.TextEditor.setText (/opt/atom/resources/app.asar/src/text-editor.js:780:26)
    at module.exports (~/.atom/packages/linter-xo/node_modules/atom-set-text/index.js:14:9)
    at atom-text-editor.XOFix (~/.atom/packages/linter-xo/index.js:95:4)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:29.9.0 core:save (atom-text-editor.editor.is-focused)
  9x -0:27.1.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:23.7.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:17.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:16.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:16 core:cancel (atom-text-editor.editor.is-focused)
     -0:12.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.9.0 linter:lint (atom-text-editor.editor)
     -0:05.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 XO:Fix (atom-text-editor.editor)
     -0:01.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
atom-ternjs, v0.13.2
autocomplete-python, v1.6.1
git-hide, v0.1.2
git-plus, v5.13.0
language-gitignore, v0.2.0
linter, v1.11.3
linter-pep8, v1.2.1
linter-sass-lint, v1.1.0
linter-xo, v0.12.0
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
php-integrator-autocomplete-plus, v0.5.2

# Dev
No dev packages
```

**Comment by SparserLogic** [comment]
Same issue.
