### ISSUE TITLE
chdir bad argument

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/atom-linter-xo#14]
```
TypeError: Bad argument.
    at TypeError (native)
    at process.chdir (/Users/wmertens/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:18:9)
    at Object.lint (/Users/wmertens/.atom/packages/linter-xo/index.js:21:10)
    at ...
```

I don't have time to look into it right now but I'm reasonably sure it's because of pkgdir not finding a package.json and then chdir getting called with the wrong thing.

**Comment by sindresorhus** [comment]
The plugin is no longer using `chdir`, so I don't think this is an issue anymore.
