### ISSUE TITLE
Failed to load the linter-xo package

### ISSUE THREAD

**Issue by enlacee** [sindresorhus/atom-linter-xo#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-66-generic
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.12.0

### Stack Trace

Failed to load the linter-xo package

```
At /home/anb/.atom/packages/linter-xo/index.js:2
import path from 'path';
^^^^^^
Unexpected reserved word

/home/anb/.atom/packages/linter-xo/index.js:2
import path from 'path';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
    at /usr/share/atom/resources/app/src/package.js:189:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view"
    ],
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter-xo, v0.12.0
minimap, v4.13.2

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Upgrade Atom

**Comment by enlacee** [comment]
oks thanks

**Comment by Pszek** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Windows 7 64
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.13.0


### Stack Trace

Failed to load the linter-xo package

```
At Cannot find module 'acorn-jsx/inject'

Error: Cannot find module 'acorn-jsx/inject'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\node_modules\espree\espree.js:65:16)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\lib\eslint.js:14:14)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\lib\api.js:9:13)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\index.js:3:14)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "behave-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
behave-theme, v1.6.0
language-babel, v2.15.5
linter, v1.11.3
linter-xo, v0.13.0
nucleus-dark-ui, v0.7.10

# Dev
No dev packages
```

**Comment by perryprog** [comment]
Getting same error (`Cannot find module 'sb-npm-path'`) in `Atom 1.18.0-beta0`. Any ETA on support for `1.18`?

**Comment by Arcanemagus** [comment]
@perryprog That is very much _not_ the same error. It sounds like your package didn't install properly so the first thing I would recommend trying is to re-install the package.

**Comment by perryprog** [comment]
OK, I'm blind. Sorry! For some reason Atom said this was the same issue -_-
