### ISSUE TITLE
Failed to load xo-linter on win

### ISSUE THREAD

**Issue by Pszek** [sindresorhus/atom-linter-xo#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**:  Windows 7 64-bit
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.13.0

### Stack Trace

Failed to load the linter-xo package

```
At Cannot find module 'acorn-jsx/inject'

Error: Cannot find module 'acorn-jsx/inject'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\node_modules\espree\espree.js:65:16)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\lib\eslint.js:14:14)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\node_modules\eslint\lib\api.js:9:13)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Cini\.atom\packages\linter-xo\node_modules\xo\index.js:3:14)
    at Module._compile (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Cini\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "behave-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
behave-theme, v1.6.0
language-babel, v2.15.5
linter, v1.11.3
linter-xo, v0.13.0
nucleus-dark-ui, v0.7.10

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Looks like a typical npm install corruption. Try reinstalling the package.

**Comment by Pszek** [comment]
The problem is also in Sublime and VS Code (though different error messages). Closing issue
