### ISSUE TITLE
ava/no-ignored-files doesn't seem to respect ava's "files" config

### ISSUE THREAD

**Issue by bojand** [sindresorhus/atom-linter-xo#23]
Not sure where this should go... here or in [eslint-plugin-ava](https://github.com/sindresorhus/eslint-plugin-ava). I am probably doing something wrong, but I can't figure it out. I am using Atom `1.6.2`, `ava@0.14.0`, `xo@0.14.0`. My relevant `package.json` configs:

```
"ava": {
    "files": [
      "test/*.test.js"
    ]
  },
  "xo": {
    "envs": [
      "node",
      "es6"
    ],
    "esnext": true,
    "space": true,
    "rules": {
      "babel/arrow-parens": 1,
      "babel/object-curly-spacing": 0,
      "babel/object-shorthand": 1,
      "brace-style": 1,
      "no-else-return": 1,
      "no-unused-vars": 1
    }
  },
  "directories": {
    "test": "test"
  },
```

In case it matters, I have `.babelrc`:

```
{
  "presets": ["es2015"]
}
```

Relevant scripts:

```
"test": "npm run dist && ava -v",
"dist": "node ./node_modules/babel-cli/bin/babel.js lib --out-dir dist",
```

Installed babel:

```
babel-cli@6.6.0
babel-preset-es2015@6.6.0
```

In case it's relevant I have `.eslintignore`

```
lib/
test/
node_modules
```

I have a `test` directory and 1 test file `foo.test.js`. I keep getting 

![image](https://cloud.githubusercontent.com/assets/2081100/14492604/cf383e52-0156-11e6-9e79-83fb78af2a77.png)

No matter what I try to set the `files` ava config, it doesn't help. I've even tried setting `"files"` within `"ava/no-ignored-test-files"` setting of `"xo"` config and it didn't help. 

Any insight is appreciated.

Thanks

**Comment by sindresorhus** [comment]
Ah, I think I know what the issue is. I published a new version of the Atom plugin. Can you reinstall it and try again?

**Comment by bojand** [comment]
Hello, thanks. I updated and now it seems like the linter package is crashing.

```
TypeError: Invalid Point: (NaN, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1052:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1040:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:193:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1107:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1397:59)
    at /Users/bdjurkovic/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/bdjurkovic/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/bdjurkovic/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/bdjurkovic/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/bdjurkovic/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/bdjurkovic/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/bdjurkovic/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/bdjurkovic/.atom/packages/linter/lib/message-registry.js:24:16)
```

**Comment by sindresorhus** [comment]
Can you provide a minimal example that reproduces the problem? Also make sure you're on the latest Atom Linter version.

**Comment by bojand** [comment]
Hello, ok... after digging in, I think the crash may be unrelated. I updated my Atom to `1.7.0` last night too and I think it may be related to that perhaps. Here's a [sample project](https://github.com/bojand/atom-linter-test) that causes the issue. if you clone it and do `atom .` from folder it opens it and if you click on `lib/index.js` it should crash. What's interesting is that there is actually no `xo` or `ava` configs in `package.json. I am on latest `xo` installed globally. I also have `eslint@2.6.0` installed globally if that somehow matters. I _do not_ have `ava` installed globally.

**Comment by bojand** [comment]
Further investigation... Seems output from x has changed or is not what the linter is expecting...

```
report = lintText(textEditor.getText(), {
			cwd: dir,
			filename: filePath
		});
```

returns report:

```
{
  "results":[
    {
      "filePath":"/Users/bdjurkovic/dev/nodejs/atom-linter-test/lib/index.js",
      "messages":[
        {
          "fatal":false,
          "severity":1,
          "message":"File ignored because of a matching ignore pattern. Use --no-ignore to override."
        }
      ],
      "errorCount":0,
      "warningCount":1
    }
  ],
  "errorCount":0,
  "warningCount":1
}
```

thus the `x` in `result.messages.forEach(x => {`:

```
{"fatal":false,"severity":1,"message":"File ignored because of a matching ignore pattern. Use --no-ignore to override."}
```

```
range: [
					[x.line - 1, x.column - 1],
					[x.line - 1, x.column - 1]
				]
```

ends up being `NaN`'s.

**Comment by bojand** [comment]
Could be related to the fact I have `.eslintignore` setup with the actual folder that is inspected being in `.eslintignore`. I think the issue is that `xo` uses `eslint` itself. Basically I wanted my setup to be that if I have `xo` setup to use `xo` and `atom-linter-xo` otherwise I wanted by default to use `eslint` and `atom-eslinter` in other projects, regardless if I have `.eslintrc` or `eslint` config in `package.json`. So in my projects where I have `xo` setup I thought I could just add `.eslintignore` to ignore folders that `xo` will handle. But it seems `linter` package and `xo` do not really work this way because `xo` uses `eslint` itself. So `xo` was getting the warning about ignored file(s), which doesn't have the line information.
