### ISSUE TITLE
Cannot find module 'path-exists'

### ISSUE THREAD

**Issue by silverskyvicto** [sindresorhus/atom-linter-xo#26]
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-xo](https://github.com/sindresorhus/atom-linter-xo) package, v0.16.0

### Stack Trace

Failed to activate the linter-xo package

```
At Cannot find module 'path-exists'

Error: Cannot find module 'path-exists'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/ey/.atom/packages/linter-xo/node_modules/pkg-dir/node_modules/find-up/index.js:3:18)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/ey/.atom/packages/linter-xo/node_modules/pkg-dir/index.js:3:14)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/ey/.atom/packages/linter-xo/index.js:24:15)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "linter-markdown",
      "whitespace",
      "node-resolver",
      "autohide-tree-view",
      "java-generator",
      "autocomplete-html-entities",
      "linter-jscs",
      "json-schema",
      "atom-json-editor",
      "linter-csslint",
      "quick-query"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v1.0.7
Stylus, v3.0.0
Sublime-Style-Column-Selection, v1.5.1
angularjs, v0.3.4
angularjs-snippets, v0.10.18
api-workbench, vundefined
atom-alignment, v0.12.1
atom-django, v0.3.2
atom-html-preview, v0.1.21
atom-jshint, v2.0.0
atom-python-debugger, v0.3.4
atom-react-native-autocomplete, v0.0.27
atom-react-preview, v2.0.0
atom-ternjs, v0.14.2
atomic-chrome, v0.3.0
autoclose-html, v0.23.0
autocomplete-angular-material, v0.4.0
autocomplete-modules, v1.5.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.8.1
autocomplete-ruby, v0.1.0
browser-plus, v0.0.60
build-cargo, v0.15.0
build-gradle, v0.6.0
color-picker, v2.1.1
css-snippets, v0.9.0
data-atom, v0.20.4
django-templates, v0.5.0
django-test-runner, v0.5.0
docblockr, v0.7.3
file-icons, v1.7.15
file-type-icons, v1.3.0
file-types, v0.5.2
git-diff-details, v1.3.0
git-log, v0.4.1
gulp-snippets, v0.6.2
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
imdone-atom, v1.3.29
jQuery, v1.2.4
japanese-menu, v1.8.0
javascript-snippets, v1.2.1
jshint, v1.8.5
jsonlint, v1.1.4
language-babel, vundefined
language-django, v0.1.1
language-docker, v1.1.6
language-jade, v0.7.1
language-javascript-jsx, v0.3.7
language-markdown, v0.14.1
language-mongodb, v0.3.1
language-nginx, v0.6.1
language-plantuml, v0.2.0
language-rust, v0.4.6
language-ts, v1.0.2
linter, v1.11.14
linter-bootlint, v1.0.2
linter-docker, v0.1.2
linter-eslint, vundefined
linter-htmlhint, v1.2.1
linter-javac, v1.9.4
linter-jsonlint, v1.2.5
linter-jsxhint, v0.1.2
linter-python, v2.1.7
linter-python-pep8, v0.2.0
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-rust, v0.4.6
linter-tslint, v0.10.0
linter-xo, v0.16.0
markdown-format, v2.5.1
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
markdown-table-formatter, v2.8.3
markdown-themeable-pdf, v1.1.0
merge-conflicts, v1.4.4
minimap, v4.24.6
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.1
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
node-debugger, v1.7.0
nodejs-snippets, v2.0.1
pdf-view, v0.50.0
pigments, v0.29.2
plantuml-viewer, v0.7.0
pretty-json, v1.4.1
preview-plus, v1.2.6
python-indent, v0.4.3
python-tools, v0.6.7
racer, v0.20.0
react, v0.15.0
react-es6-snippets, v0.3.0
react-snippets, v0.4.2
redux-snippets, v0.2.2
regex-railroad-diagram, v0.16.0
ruby-block, v0.3.5
rust-api-docs-helper, v0.5.1
show-ideographic-space, v1.0.1
symbols-tree-view, v0.13.2
synced-sidebar, v0.4.3
tablr, v1.3.1
tabs-to-spaces, v1.0.2
term3, v0.22.1
tornado-templates, v0.2.0
trailing-spaces, v0.3.2
tree-view-git-branch, v0.1.2
tree-view-git-status, v1.0.1
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by sindresorhus** [comment]
Probably just a corrupt install. Try reinstalling the plugin.
