### ISSUE TITLE
Failed to load the linter-xo  Package : foo is defined but never user

### ISSUE THREAD

**Issue by tahenti** [sindresorhus/atom-linter-xo#6]
/home/beya/.atom/packages/linter-xo/index.js:2
import path from 'path';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:709:34)
    at /usr/share/atom/resources/app.asar/src/package.js:188:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)

**Comment by sindresorhus** [comment]
Make sure you're on the latest Atom version.

**Comment by tahenti** [comment]
I have the atom version 1.0.0

Thanks and best regards

**Comment by sindresorhus** [comment]
The latest version is 1.1.0. Try upgrading.
