### ISSUE TITLE
Error running XO Error: Cannot find module './code-path-analysis/code-path-analyzer'

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/atom-linter-xo#85]
I've been randomly getting this error over the last few days.

```
/Users/xo/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running XO Error: Cannot find module './code-path-analysis/code-path-analyzer'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/node_modules/eslint/lib/eslint.js:19:24)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/node_modules/eslint/lib/eslint.js:1236:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/node_modules/eslint/lib/api.js:9:13)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/node_modules/eslint/lib/api.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/index.js:3:16)
    at Object.<anonymous> (/Users/xo/code/@ladjs/email/node_modules/xo/index.js:120:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /Users/xo/.atom/packages/linter-xo/lib/get-xo.js:24:9
    at exports.allowUnsafeNewFunction (/Users/xo/.atom/packages/linter-xo/node_modules/loophole/lib/loophole.js:25:14)
    at dangerouslyRequire (/Users/xo/.atom/packages/linter-xo/lib/get-xo.js:23:2)
    at /Users/xo/.atom/packages/linter-xo/lib/get-xo.js:15:11
(anonymous) @ /Users/xo/.atom/packages/linter/lib/linter-registry.js:159
```

**Comment by OmgImAlexis** [comment]
Looks like yarn fucked up somewhere.
